services:
  - type: web
    name: tiktok-media-downloader
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
